---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    base_image: centos:7
    container_name: fathom_build_container
    image_namespace: geerlingguy
    image_name: fathom

    # Fathom settings.
    fathom_manage_service: false

    # Handy utilities.
    handy_utilities:
      - curl
      - unzip

  pre_tasks:
    - name: Make the latest version of the base image available locally.
      docker_image:
        name: '{{ base_image }}'
        source: pull

    - name: Create the Docker container.
      docker_container:
        image: '{{ base_image }}'
        name: '{{ container_name }}'
        command: sleep infinity

    - name: Add the newly created container to the inventory.
      add_host:
        hostname: '{{ container_name }}'
        ansible_connection: docker

    - name: Gather facts inside the container.
      setup:
      delegate_to: '{{ container_name }}'

  roles:
    - name: geerlingguy.fathom
      delegate_to: '{{ container_name }}'

  post_tasks:
    - name: Install handy utilities.
      package:
        name: "{{ item }}"
        state: present
      with_items: "{{ handy_utilities }}"
      delegate_to: '{{ container_name }}'

    - name: Commit the container.
      command: >
        docker commit
        -c 'CMD ["fathom", "server"]'
        -c 'WORKDIR "/opt/fathom"'
        {{ container_name }} {{ image_namespace }}/{{ image_name }}:latest

    - name: Remove the container.
      docker_container:
        name: '{{ container_name }}'
        state: absent
